# Change these first
owner: 503stack # Your GitHub organization or username, where this repository lives
repo: uptimetest # The name of this repository

sites:
  - name: brg
    url: https://brg.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/brg/brreg.png
  - name: buf
    url: https://buf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/buf/buf.png
  - name: dat
    url: https://dat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dat/arbeidstilsynet.png
  - name: dibk
    url: https://dibk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dibk/dibk.png
  - name: digdir
    url: https://digdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: dihe
    url: https://dihe.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: dmf
    url: https://dmf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dmf/dmf.png
  - name: din
    url: https://din.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/din/din.jpg
  - name: dsb
    url: https://dsb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dsb/dsb.png
  - name: fd
    url: https://fd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fd/fiskeridirektoratet.png
  - name: fhi
    url: https://fhi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fhi/fhi.png
  - name: fors
    url: https://fors.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fors/fors.png
  - name: gk
    url: https://gk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/gk/gjenopptakelseskommisjonen.png
  - name: hdir
    url: https://hdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hdir/helsedirektoratet.png
  - name: hemit
    url: https://hemit.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hemit/hemit.svg
  - name: hi
    url: https://hi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hi/havforskningsinstituttet.png
  - name: hmrhf
    url: https://hmrhf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hmrhf/hmrhf.png
  - name: ikta
    url: https://ikta.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ikta/ikta.png
  - name: k1103
    url: https://k1103.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/k1103/k1103.png
  - name: krt
    url: https://krt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/krt/krt.png
  - name: ksdigi
    url: https://ksdigi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ksdigi/ksdigi.png
  - name: kv
    url: https://kv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/kv/kartverket.png
  - name: kyv
    url: https://kyv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/kyv/kyv.png
  - name: lt
    url: https://lt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/lt/lt.png
  - name: lts
    url: https://lts.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/lts/lts.png
  - name: mat
    url: https://mat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/mat/mat.png
  - name: mdir
    url: https://mdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/mdir/mdir.png
  - name: nb
    url: https://nb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nb/norgesbank.png
  - name: nbib
    url: https://nbib.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nbib/nasjonalbiblioteket.png
  - name: nfk
    url: https://nfk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nfk/nordre-follo-kommune-navnetrekk-bredde-2-linje-rgb.svg
  - name: nhn
    url: https://nhn.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nhn/nhn.png
  - name: nkom
    url: https://nkom.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nkom/nkom.png
  - name: nkr
    url: https://nkr.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nkr/kulturradet.png
  - name: nav
    url: https://nav.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nav/nav.png
  - name: npe
    url: https://npe.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/npe/npe.png
  - name: nsm
    url: https://nsm.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nsm/nsm.png
  - name: oed
    url: https://oed.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/oed/oed.png
  - name: ok
    url: https://ok.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ok/ok.png
  - name: oko
    url: https://oko.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/oko/oko.png
  - name: pat
    url: https://pat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/pat/pat.png
  - name: ssikt
    url: https://ssikt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ssikt/ssikt.png
  - name: sfd
    url: https://sfd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/sfd/sfd.png
  - name: sfvt
    url: https://sfvt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/sfvt/sfvt.png
  - name: skd
    url: https://skd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/skd/skd.png
  - name: slv
    url: https://slv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: spk
    url: https://spk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: srf
    url: https://srf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/srf/srf.png
  - name: ssb
    url: https://ssb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ssb/ssb_dark.png
  - name: staf
    url: https://staf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/staf/staf.png
  - name: stami
    url: https://stami.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/stami/stami.png
  - name: svv
    url: https://svv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/svv/svv.png
  - name: tad
    url: https://tad.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/tad/tad.png
  - name: tra
    url: https://tra.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/tra/tra.png
  - name: ttd
    url: https://ttd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: udi
    url: https://udi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/udi/udi.png
  - name: udir
    url: https://udir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/udir/udir.png
  - name: valg
    url: https://valg.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/valg/valg.png
  - name: nve
    url: https://nve.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: vigo
    url: https://vigo.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 503stack.xyz
  baseUrl: /uptimetest
  logoUrl: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/digdir.png
  favicon: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/favicon.ico
  name: Altinn tt02
  introTitle: "**Altinn Test** uptime monitor and status page."
  introMessage: Powered entirely by GitHub
  navbar:
    - title: Status
      href: /uptimetest
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
