# Change these first
owner: 503stack # Your GitHub organization or username, where this repository lives
repo: uptimetest # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 503stack.xyz
  baseUrl: /uptimetest
  logoUrl: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/digdir.png
  favicon: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/favicon.ico
  name: Altinn tt02
  introTitle: "**Altinn Test** uptime monitor and status page."
  introMessage: Powered entirely by GitHub
  navbar:
    - title: Status
      href: /uptimetest
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
