# Change these first
owner: 503stack # Your GitHub organization or username, where this repository lives
repo: uptimetest # The name of this repository
runner: "[self-hosted]"

sites:
  - name: brg-tt02-aks
    url: https://brg.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/brg/brreg.png
  - name: buf-tt02-aks
    url: https://buf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/buf/buf.png
  - name: dat-tt02-aks
    url: https://dat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dat/arbeidstilsynet.png
  - name: dibk-tt02-aks
    url: https://dibk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dibk/dibk.png
  - name: digdir-tt02-aks
    url: https://digdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/digdir/digdir.png
  - name: dihe-tt02-aks
    url: https://dihe.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: dmf-tt02-aks
    url: https://dmf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dmf/dmf.png
  - name: din-tt02-aks
    url: https://din.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/din/din.jpg
  - name: dsb-tt02-aks
    url: https://dsb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/dsb/dsb.png
  - name: fd-tt02-aks
    url: https://fd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fd/fiskeridirektoratet.png
  - name: fhi-tt02-aks
    url: https://fhi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fhi/fhi.png
  - name: fors-tt02-aks
    url: https://fors.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/fors/fors.png
  - name: gk-tt02-aks
    url: https://gk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/gk/gjenopptakelseskommisjonen.png
  - name: hdir-tt02-aks
    url: https://hdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hdir/helsedirektoratet.png
  - name: hemit-tt02-aks
    url: https://hemit.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hemit/hemit.svg
  - name: hi-tt02-aks
    url: https://hi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/hi/havforskningsinstituttet.png
  - name: ikta-tt02-aks
    url: https://ikta.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ikta/ikta.png
  - name: k1103-tt02-aks
    url: https://k1103.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/k1103/k1103.png
  - name: krt-tt02-aks
    url: https://krt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/krt/krt.png
  - name: ksdigi-tt02-aks
    url: https://ksdigi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ksdigi/ksdigi.png
  - name: kv-tt02-aks
    url: https://kv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/kv/kartverket.png
  - name: kyv-tt02-aks
    url: https://kyv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/kyv/kyv.png
  - name: lt-tt02-aks
    url: https://lt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/lt/lt.png
  - name: lts-tt02-aks
    url: https://lts.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/lts/lts.png
  - name: mat-tt02-aks
    url: https://mat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/mat/mat.png
  - name: mdir-tt02-aks
    url: https://mdir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/mdir/mdir.png
  - name: nb-tt02-aks
    url: https://nb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nb/norgesbank.png
  - name: nbib-tt02-aks
    url: https://nbib.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nbib/nasjonalbiblioteket.png
  - name: nfk-tt02-aks
    url: https://nfk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nfk/nordre-follo-kommune-navnetrekk-bredde-2-linje-rgb.svg
  - name: nhn-tt02-aks
    url: https://nhn.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nhn/nhn.png
  - name: nkom-tt02-aks
    url: https://nkom.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nkom/nkom.png
  - name: nkr-tt02-aks
    url: https://nkr.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nkr/kulturradet.png
  - name: nav-tt02-aks
    url: https://nav.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nav/nav.png
  - name: npd-tt02-aks
    url: https://npd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/npd/npd.svg
  - name: npe-tt02-aks
    url: https://npe.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/npe/npe.png
  - name: nsm-tt02-aks
    url: https://nsm.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nsm/nsm.png
  - name: oed-tt02-aks
    url: https://oed.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/oed/oed.png
  - name: ok-tt02-aks
    url: https://ok.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ok/ok.png
  - name: oko-tt02-aks
    url: https://oko.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/oko/oko.png
  - name: pat-tt02-aks
    url: https://pat.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/pat/pat.png
  - name: ssikt-tt02-aks
    url: https://ssikt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ssikt/ssikt.png
  - name: sfd-tt02-aks
    url: https://sfd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/sfd/sfd.png
  - name: sfvt-tt02-aks
    url: https://sfvt.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/sfvt/sfvt.png
  - name: skd-tt02-aks
    url: https://skd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/skd/skd.png
  - name: slv-tt02-aks
    url: https://slv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: spk-tt02-aks
    url: https://spk.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: srf-tt02-aks
    url: https://srf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/srf/srf.png
  - name: ssb-tt02-aks
    url: https://ssb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ssb/ssb_dark.png
  - name: staf-tt02-aks
    url: https://staf.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/staf/staf.png
  - name: stami-tt02-aks
    url: https://stami.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/stami/stami.png
  - name: svv-tt02-aks
    url: https://svv.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/svv/svv.png
  - name: tad-tt02-aks
    url: https://tad.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/tad/tad.png
  - name: tra-tt02-aks
    url: https://tra.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/tra/tra.png
  - name: ttd-tt02-aks
    url: https://ttd.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/ttd/ttd.png
  - name: udi-tt02-aks
    url: https://udi.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/udi/udi.png
  - name: udir-tt02-aks
    url: https://udir.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/udir/udir.png
  - name: valg-tt02-aks
    url: https://valg.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/valg/valg.png
  - name: skm-tt02-aks
    url: https://skm.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/skm/skm.png
  - name: hb-tt02-aks
    url: https://hb.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: nve-tt02-aks
    url: https://nve.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
  - name: nokut-tt02-aks
    url: https://nokut.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
    icon: https://altinncdn.no/orgs/nokut/nokut.svg
  - name: vigo-tt02-aks
    url: https://vigo.apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 503stack.xyz
  baseUrl: /uptimetest
  logoUrl: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/digdir.png
  favicon: https://raw.githubusercontent.com/503stack/uptimetest/master/assets/favicon.ico
  name: Altinn tt02
  introTitle: "**Altinn Test** uptime monitor and status page."
  introMessage: Powered entirely by GitHub
  navbar:
    - title: Prod
      href: /uptimeprod
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
