name: Update Sites in .upptimerc.yml

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update-sites.yml"
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  update-sites:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download altinn-orgs.json
        run: curl -sSL -o altinn-orgs.json https://altinncdn.no/orgs/altinn-orgs.json

      - name: Update .upptimerc.yml with tt02 orgs
        run: |
          # Generate the new sites section
          echo "sites:" > sites_new.yml
          jq -r '
            .orgs | to_entries[]
            | select(.value.environments != null and (.value.environments | index("tt02")))
            | (
                "  - name: \(.key)-tt02-aks\n" +
                "    url: https://\(.key).apps.tt02.altinn.no/kuberneteswrapper/api/v1/deployments\n" +
                "    ipv6: true" +
                (
                  if (.value.logo // "") != ""
                  then "\n    icon: \(.value.logo)"
                  else ""
                  end
                )
              )
          ' altinn-orgs.json >> sites_new.yml

          # Create a backup of the original file
          cp .upptimerc.yml .upptimerc.yml.backup

          # Extract everything before the sites section
          awk '/^sites:/ {exit} {print}' .upptimerc.yml > .upptimerc.yml.new

          # Add the new sites section
          cat sites_new.yml >> .upptimerc.yml.new

          # Extract everything after the sites section (starting from the next top-level key)
          awk '
          BEGIN { in_sites = 0; sites_ended = 0 }
          /^sites:/ { in_sites = 1; next }
          /^[a-zA-Z]/ && in_sites { sites_ended = 1; in_sites = 0 }
          sites_ended { print }
          ' .upptimerc.yml >> .upptimerc.yml.new

          # Replace the original file
          mv .upptimerc.yml.new .upptimerc.yml

          # Clean up temporary files
          rm -f sites_new.yml .upptimerc.yml.backup

      - name: Show updated .upptimerc.yml
        run: cat .upptimerc.yml

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .upptimerc.yml
          git diff --staged --quiet || git commit -m "Update sites list with latest tt02 orgs"
          git push
